:PROPERTIES:
:ID:       D56FD870-397C-44A6-A04F-D9E1241A9641
:END:
#+title: Org Roam

* Commands
:PROPERTIES:
:ID:       E04776E9-856B-4073-ADAF-9C8ECFC38C3C
:ROAM_ALIASES: "Org Roam Commands"
:END:

** ~org-roam-db-sync~
Rebuilds the cache manually to re-index for searching, etc.

Use this after a pull from the notes git repo. The
~org-roam-db-autosync-mode~ function is called in the Emacs init so a
restart would accomplish the same thing.

** ~org-roam-node-insert~

Inserts a new node.


** ~org-roam-node-find~

Either finds or inserts a new node.


** ~org-id-get-create~

Creates an id for a top-level header that makes the header into a node.


* Actions
** Find or create a note
Use this when you think of a new note when not already in Org Roam context.

M-x org-roam-node-find (C-c n f)

** Find or create a new note and link at point
Use this when editing a note and think of a new note and want to create and link to the new note from the current note.

M-x org-roam-node-insert (C-c n i)

** Visit an note link
Use this to visit a note linked in the current note.

M-x org-open-at-point (C-c C-o)


* Notes

** Using spaces in minibuffer
The space bar is mapped to completion in the minibuffer so when
creating or searching for nodes containing spaces, use ~C-q <space>~
to insert a space.
